  DROP TABLE IF EXISTS t3;
  CREATE TABLE t3(a TEXT, b TEXT, c INTEGER);
  INSERT INTO t3 VALUES    ('HH', 'bb', 355), ('CC', 'aa', 158), ('BB', 'aa', 399),     ('FF', 'bb', 938), ('HH', 'aa', 480), ('FF', 'bb', 870),     ('JJ', 'aa', 768), ('JJ', 'aa', 899), ('GG', 'bb', 929),     ('II', 'bb', 421), ('GG', 'bb', 844), ('FF', 'bb', 574),     ('CC', 'bb', 822), ('GG', 'bb', 938), ('BB', 'aa', 660),     ('HH', 'aa', 979), ('BB', 'bb', 792), ('DD', 'aa', 845),     ('JJ', 'bb', 354), ('FF', 'bb', 295), ('JJ', 'aa', 234),     ('BB', 'bb', 840), ('AA', 'aa', 934), ('EE', 'aa', 113),     ('AA', 'bb', 309), ('BB', 'aa', 412), ('AA', 'aa', 911),     ('AA', 'bb', 572), ('II', 'aa', 398), ('II', 'bb', 250),     ('II', 'aa', 652), ('BB', 'bb', 633), ('AA', 'aa', 239),     ('FF', 'aa', 670), ('BB', 'bb', 705), ('HH', 'bb', 963),     ('CC', 'bb', 346), ('II', 'bb', 671), ('BB', 'aa', 247),     ('AA', 'aa', 223), ('GG', 'aa', 480), ('HH', 'aa', 790),     ('FF', 'aa', 208), ('BB', 'bb', 711), ('EE', 'aa', 777),     ('DD', 'bb', 716), ('CC', 'aa', 759), ('CC', 'aa', 430),     ('CC', 'aa', 607), ('DD', 'bb', 794), ('GG', 'aa', 148),     ('GG', 'aa', 634), ('JJ', 'bb', 257), ('DD', 'bb', 959),     ('FF', 'bb', 726), ('BB', 'aa', 762), ('JJ', 'bb', 336),     ('GG', 'aa', 335), ('HH', 'bb', 330), ('GG', 'bb', 160),     ('JJ', 'bb', 839), ('FF', 'aa', 618), ('BB', 'aa', 393),     ('EE', 'bb', 629), ('FF', 'aa', 667), ('AA', 'bb', 870),     ('FF', 'bb', 102), ('JJ', 'aa', 113), ('DD', 'aa', 224),     ('AA', 'bb', 627), ('HH', 'bb', 730), ('II', 'bb', 443),     ('HH', 'bb', 133), ('EE', 'bb', 252), ('II', 'bb', 805),     ('BB', 'bb', 786), ('EE', 'bb', 768), ('HH', 'bb', 683),     ('DD', 'bb', 238), ('DD', 'aa', 256);
  DROP TABLE IF EXISTS t1;
  CREATE TABLE t1(a REAL, b INTEGER);
  INSERT INTO t1 VALUES      (5, 10), (10, 20), (13, 26), (13, 26),       (15, 30), (20, 40), (22,80), (30, 90);
  DROP TABLE IF EXISTS t1;
  CREATE TABLE t1(a INTEGER, b INTEGER);
  INSERT INTO t1 VALUES    (NULL, 1), (NULL, 2), (NULL, 3), (10, 4), (10, 5);
  SELECT sum(b) OVER (    ORDER BY a RANGE BETWEEN 5 PRECEDING AND 10 FOLLOWING  ) FROM t1 ORDER BY 1;
  SELECT sum(b) OVER (    ORDER BY a DESC RANGE BETWEEN 5 PRECEDING AND 10 FOLLOWING  ) FROM t1 ORDER BY 1;
  INSERT INTO t3 VALUES    (NULL, 'bb', 355), (NULL, 'cc', 158), (NULL, 'aa', 399),     ('JJ', NULL, 839), ('FF', NULL, 618), ('BB', NULL, 393),     (NULL, 'bb', 629), (NULL, NULL, 667), (NULL, NULL, 870);
  DROP TABLE IF EXISTS t2;
  CREATE TABLE t2(a TEXT, b INTEGER);
  INSERT INTO t2 VALUES('A', NULL);
  INSERT INTO t2 VALUES('B', NULL);
  INSERT INTO t2 VALUES('C', 1);
  DROP TABLE IF EXISTS t2;
  CREATE TABLE t2(a INTEGER, b INTEGER);
  INSERT INTO t2 VALUES(1, 65);
  INSERT INTO t2 VALUES(2, NULL);
  INSERT INTO t2 VALUES(3, NULL);
  INSERT INTO t2 VALUES(4, NULL);
  INSERT INTO t2 VALUES(5, 66);
  INSERT INTO t2 VALUES(6, 67);
  DROP TABLE IF EXISTS tx;
  CREATE TABLE tx(a INTEGER PRIMARY KEY);
  INSERT INTO tx VALUES(1), (2), (3), (4), (5), (6);
  DROP TABLE IF EXISTS map;
  CREATE TABLE map(v INTEGER PRIMARY KEY, t TEXT);
  INSERT INTO map VALUES    (1, 'odd'), (2, 'even'), (3, 'odd'),     (4, 'even'), (5, 'odd'), (6, 'even');
  SELECT sum(a) OVER (    PARTITION BY (      SELECT t FROM map WHERE v=a    ) ORDER BY a  ) FROM tx;
  SELECT sum(a) OVER win FROM tx  WINDOW win AS (    PARTITION BY (      SELECT t FROM map WHERE v=a    ) ORDER BY a  );
  WITH map2 AS (    SELECT * FROM map  )  SELECT sum(a) OVER (    PARTITION BY (      SELECT t FROM map2 WHERE v=a    ) ORDER BY a  ) FROM tx;
  DROP TABLE IF EXISTS t1;
  DROP TABLE IF EXISTS t2;
  CREATE TABLE t1(a INTEGER);
  CREATE TABLE t2(y INTEGER);
  SELECT (    SELECT max(a) OVER ( ORDER BY (SELECT sum(a) FROM t1) )         + min(a) OVER()   )  FROM t1;
