SET bytea_output TO escape;
  select armor('');
 select armor('test');
 select dearmor(armor(''));
 select dearmor(armor('zooka'));
  select armor('0123456789abcdef0123456789abcdef0123456789abcdef 0123456789abcdef0123456789abcdef0123456789abcdef');
  select dearmor(' a pgp msg:  Comment: Some junk  em9va2E=  =D5cR   select dearmor(' wrong packet:  d3Jvbmc= =vCYP  right packet:  cmlnaHQ= =nbpj  use only first packet  d3Jvbmc= =vCYP ');
  select dearmor('  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' foo:  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' em9va2E= =ZZZZ ');
  select * from pgp_armor_headers('  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' foo:  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' fookey: foovalue barkey: barvalue  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' insane:key :  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' insane:key : text value here  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' long: this value is more than 76 characters long, but it should still parse correctly as that''s permitted by RFC 4880  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' long: this value is more than 76 characters long, but it should still long: parse correctly as that''s permitted by RFC 4880  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' long: this value is more than long: 76 characters long, but it should still long: parse correctly as that''s permitted by RFC 4880  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' emptykey: long: this value is more than emptykey: long: 76 characters long, but it should still emptykey: long: parse correctly as that''s permitted by RFC 4880 emptykey:  em9va2E= =ZZZZ ');
  select * from pgp_armor_headers(' Comment: dat1.blowfish.sha1.mdc.s2k3.z0  jA0EBAMCfFNwxnvodX9g0jwB4n4s26/g5VmKzVab1bX1SmwY7gvgvlWdF3jKisvS yA6Ce1QTMK3KdL2MPfamsTUSAML8huCJMwYQFfE= =JcP+ ');
  select * from pgp_armor_headers(replace(' fookey: foovalue barkey: barvalue  em9va2E= =ZZZZ ', E'\n', E'\r\n'));
  select armor('zooka', array['foo'], array['bar']);
 select armor('zooka', array['Version', 'Comment'], array['Created by pgcrypto', 'PostgreSQL, the world''s most advanced open source database']);
 select * from pgp_armor_headers( armor('zooka', array['Version', 'Comment'], array['Created by pgcrypto', 'PostgreSQL, the world''s most advanced open source database']));
  select armor('', array['foo'], array['too', 'many']);
 select armor('', array['too', 'many'], array['foo']);
 select armor('', array[['']], array['foo']);
 select armor('', array['foo'], array[['']]);
 select armor('', array[null], array['foo']);
 select armor('', array['foo'], array[null]);
 select armor('', '[0:0]={"foo"}', array['foo']);
 select armor('', array['foo'], '[0:0]={"foo"}');
 select armor('', array[E'embedded\nnewline'], array['foo']);
 select armor('', array['foo'], array[E'embedded\nnewline']);
 select armor('', array['embedded: colon+space'], array['foo']);
 